### ISSUE TITLE
Exception in thread "main" java.io.UncheckedIOException

### ISSUE THREAD

**Issue by sy-project** [Luohuayu/FoxServer#8]
```
Exception in thread "main" java.io.UncheckedIOException: java.io.IOException: Invalid paths argument, contained no existing paths: [libraries\net\minecraft\server\1.18.2-20220404.173914\server-1.18.2-20220404.173914-extra.jar]
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:74)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:50)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:42)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:93)
Caused by: java.io.IOException: Invalid paths argument, contained no existing paths: [libraries\net\minecraft\server\1.18.2-20220404.173914\server-1.18.2-20220404.173914-extra.jar]
        ... 5 more
```
my error is that code.

what should i do?

i tried run.bat file.

in run.bat
```
@echo off
java -Xms60G -Xmx60G -jar FoxServer-1.18.2-dc251db-server.jar
pause
```

**Comment by XionioXMaster** [comment]
-Xms60G -Xmx60G omg

**Comment by Kotori0629** [comment]
Foxserver is currently in the development stage, coming soon!

**Comment by Luohuayu** [comment]
FoxServer is under development, please following our project.
